ThrottledStream
meogol/Zion pull request #33
Opened 2022-03-01 17:53 UTC by ONEPANTSU

https://stackoverflow.com/questions/371032/bandwidth-throttling-in-c-sharp

2022-03-02 07:17 UTC, meogol requested changes

2022-03-02 07:17 UTC, meogol commented on Assets/Scripts/Phone/Signal/ThrottledStream.cs
> +        }
Идеальная обработка ошибок- все сломалось, ну и фиг с ним

2022-03-02 07:19 UTC, EugeneFolkast commented on Assets/Scripts/Phone/Signal/Signal.cs
> +        // parentStream - ����� ������
Кодировка

2022-03-02 07:34 UTC, CoNNoR51 requested changes
учитывая остальные комментарии, реквест не может быть одобрен

2022-03-02 07:35 UTC, vanotuvanov reviewed
учитывая остальные комментарии, реквест не может быть одобрен

2022-03-03 07:15 UTC, meogol requested changes
Методы должны возвращать значения и присваивать их в контрольном методе. Не хорошо, когда по коду приходится искать, где у тебя используются глобальные переменные. Да и в общем, в части глобалок необходимости просто нет

2022-03-03 07:15 UTC, meogol commented on Assets/Scripts/Phone/Signal/Signal.cs
> +    public void ChangePower(float distance, int collision, float radius, int countOfUsers)
ты сломал тесты. По хорошему все методы должны возвращать значения

2022-03-03 07:31 UTC, vanotuvanov approved these changes

2022-03-03 07:35 UTC, meogol approved these changes

2022-03-03 07:41 UTC, vanotuvanov approved these changes

2022-03-03 09:15 UTC, EugeneFolkast approved these changes

2022-03-03 09:16 UTC, merged